<?php
/**
 * Created by PhpStorm.
 * User: myles
 * Date: 19/4/2017
 * Time: 11:03
 */

namespace LTE;


class Embed extends AdminLte2
{
    public function head()
    {
        return parent::head(); // TODO: Change the autogenerated stub
    }

    public function header()
    {
        return parent::header(); // TODO: Change the autogenerated stub
    }

    public function html()
    {
        $html=[];
        $html[]=$this->head();
        $html[]=$this->body();
        $html[]=$this->scripts();
        $html[]='<aside class="right-side">';
        return implode("",$html);
    }

    public function lang()
    {
        return parent::lang(); // TODO: make sure the value is among one of available options (en/fr)
    }
}